"""Added user_uid column in UserToken

Revision ID: 0ffcef720e40
Revises: 4882f174ce31
Create Date: 2025-03-13 15:16:19.015327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffcef720e40'
down_revision: Union[str, None] = '4882f174ce31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_uid', table_name='users')
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.add_column('user_tokens', sa.Column('user_uid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.create_index('ix_users_uid', 'users', ['uid'], unique=False)
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.drop_column('user_tokens', 'user_uid')
    # ### end Alembic commands ###
