"""Changes in product table

Revision ID: 1143e21396ce
Revises: 4a77c5d7e3f4
Create Date: 2025-04-02 15:39:33.711907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1143e21396ce'
down_revision: Union[str, None] = '4a77c5d7e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_uid', table_name='products')
    op.drop_column('products', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_index('ix_products_uid', 'products', ['uid'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    # ### end Alembic commands ###
