"""Removing rating connection again

Revision ID: 12f589b7b889
Revises: 87b3b021d221
Create Date: 2026-01-28 07:56:33.637885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f589b7b889'
down_revision: Union[str, None] = '87b3b021d221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratings_product_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_user_id_fkey', 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    op.drop_column('ratings', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ratings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('ratings_user_id_fkey', 'ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key('ratings_product_id_fkey', 'ratings', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
