"""Adding Discount amount column

Revision ID: 2d243ec8dee4
Revises: 43af53309d8d
Create Date: 2025-04-07 08:23:12.569216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d243ec8dee4'
down_revision: Union[str, None] = '43af53309d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('amount_discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'amount_discount')
    # ### end Alembic commands ###
