"""Bug fixing with code

Revision ID: 3ba8d1bf73c7
Revises: 2d243ec8dee4
Create Date: 2025-04-10 15:19:26.784411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba8d1bf73c7'
down_revision: Union[str, None] = '2d243ec8dee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
