"""Added uid column

Revision ID: 4882f174ce31
Revises: b198aef01b18
Create Date: 2025-03-13 15:03:42.167516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4882f174ce31'
down_revision: Union[str, None] = 'b198aef01b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=300), nullable=False))
    op.add_column('products', sa.Column('count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_description'), 'products', ['description'], unique=False)
    op.add_column('users', sa.Column('uid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_column('users', 'uid')
    op.drop_index(op.f('ix_products_description'), table_name='products')
    op.drop_column('products', 'count')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
