"""Readding ratings connections

Revision ID: 6707115b61f9
Revises: 12f589b7b889
Create Date: 2026-01-28 07:57:29.912617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6707115b61f9'
down_revision: Union[str, None] = '12f589b7b889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('ratings', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'product_id')
    op.drop_column('ratings', 'user_id')
    # ### end Alembic commands ###
