"""Users table uid is primary key now

Revision ID: 7752444f0e90
Revises: 0ffcef720e40
Create Date: 2025-03-13 15:17:48.376276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7752444f0e90'
down_revision: Union[str, None] = '0ffcef720e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tokens_user_id_fkey', 'user_tokens', type_='foreignkey')
    op.drop_column('user_tokens', 'user_id')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.add_column('user_tokens', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_tokens_user_id_fkey', 'user_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
