"""Removing the ratings connections

Revision ID: 87b3b021d221
Revises: 3c68dce4fe6b
Create Date: 2026-01-28 07:55:24.717183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b3b021d221'
down_revision: Union[str, None] = '3c68dce4fe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
