"""Uid became id

Revision ID: 90905d1a5833
Revises: 7752444f0e90
Create Date: 2025-03-13 15:18:13.575591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90905d1a5833'
down_revision: Union[str, None] = '7752444f0e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_tokens_user_uid_fkey', 'user_tokens', type_='foreignkey')
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_index('ix_users_uid', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'uid')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('user_tokens', 'user_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_uid', 'users', ['uid'], unique=True)
    op.drop_column('users', 'id')
    op.add_column('user_tokens', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key('user_tokens_user_uid_fkey', 'user_tokens', 'users', ['user_uid'], ['uid'])
    op.drop_column('user_tokens', 'user_id')
    # ### end Alembic commands ###
