"""Foreign relationship

Revision ID: ad9dd509326f
Revises: 3ba8d1bf73c7
Create Date: 2025-04-10 15:22:21.865977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9dd509326f'
down_revision: Union[str, None] = '3ba8d1bf73c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
