"""Added Products Table

Revision ID: b198aef01b18
Revises: c4934ba03e7f
Create Date: 2024-11-20 16:56:36.787789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b198aef01b18'
down_revision: Union[str, None] = 'c4934ba03e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('original_price', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('percentage_discount', sa.Integer(), nullable=False),
    sa.Column('offer_expiration_date', sa.Date(), nullable=True),
    sa.Column('product_image', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
