"""Setting default for product id

Revision ID: d65084411aef
Revises: 87539e7220ca
Create Date: 2025-03-13 16:37:59.476463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65084411aef'
down_revision: Union[str, None] = '87539e7220ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_products_uid'), 'products', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_uid'), table_name='products')
    op.drop_column('products', 'uid')
    # ### end Alembic commands ###
