"""Recreating user id

Revision ID: ef97b4d4101a
Revises: 87539e7220ca
Create Date: 2025-03-13 16:21:03.196726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef97b4d4101a'
down_revision: Union[str, None] = '90905d1a5833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tokens_user_id_fkey', 'user_tokens', type_='foreignkey')
    op.drop_column('users', 'id')
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id')
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###
